name: my_flutter_app  # Replace with your project's name
description: A new Dart project

environment:
  sdk: ">=2.12.0 <4.0.0"  # Specify a suitable Dart SDK version range.

dependencies:
  http: ^0.13.3  # Use the latest version, or specify a specific version.
